[SPARK-56592][K8S] Skip upgrading setuptools in K8s PySpark Dockerfile
### What changes were proposed in this pull request?

This is an alternative to SPARK-56583 (https://github.com/apache/spark/pull/55492), which adds `--break-system-packages` to `pip3 install --no-cache-dir --upgrade setuptools` to fix the

```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    ...
note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

actually, similar to `pip`, `python3-setuptools` is installed already too, we can simply remove the upgrade

```
# apt install -y --no-install-recommends python3 python3-pip
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libpython3-stdlib libpython3.12-minimal libpython3.12-stdlib libreadline8t64 libsqlite3-0 media-types netbase python3-minimal python3-pkg-resources python3-setuptools python3-wheel python3.12 python3.12-minimal
  readline-common
...
```

### Why are the changes needed?

A better alternative to SPARK-56583, eliminate the `--break-system-packages` usage.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass GHA.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #55504 from pan3793/skip-setuptools.

Authored-by: Cheng Pan <pan3793@gmail.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>