[SPARK-56209][BUILD][FOLLOWUP] Exclude Netty transitive dependencies from Vert.x in Kubernetes modules
### What changes were proposed in this pull request?
This PR adds Netty exclusions to the `vertx-core` and `vertx-web-client` dependencies in both `resource-managers/kubernetes/core/pom.xml` and `resource-managers/kubernetes/integration-tests/pom.xml`.

```xml
<exclusions>
  <exclusion>
    <groupId>io.netty</groupId>
    <artifactId>*</artifactId>
  </exclusion>
</exclusions>
```

### Why are the changes needed?
Fix maven daily tests:

- https://github.com/apache/spark/actions/runs/23947759281/job/69847651473

```
*** RUN ABORTED ***
A needed class was not found. This could be due to an error in your runpath. Missing class: io/netty/channel/IoHandler
  java.lang.NoClassDefFoundError: io/netty/channel/IoHandler
  at java.base/java.lang.ClassLoader.defineClass1(Native Method)
  at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
  at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
  at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
  at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
  at org.apache.spark.network.util.NettyUtils.createEventLoop(NettyUtils.java:78)
  ...
  Cause: java.lang.ClassNotFoundException: io.netty.channel.IoHandler
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
  at java.base/java.lang.ClassLoader.defineClass1(Native Method)
  at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
  at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
  at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
  at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
  ...
[WARNING] The requested profile "hive" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:2.2.0:test (test) on project spark-kubernetes_2.13: There are test failures -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :spark-kubernetes_2.13

Error: Process completed with exit code 1.
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
test with maven: https://github.com/LuciferYang/spark/runs/69873815559

![image](https://github.com/user-attachments/assets/fdbbdbf8-553d-4716-9602-e1ee4ae8bc63)

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #55188 from LuciferYang/fix-vertx-netty-exclusion.

Authored-by: yangjie01 <yangjie01@baidu.com>
Signed-off-by: yangjie01 <yangjie01@baidu.com>